### ISSUE TITLE
Create simple notebooks for the simplest use cases

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#1]
Following notebooks:
- Creating a chromatogram / fragment pickle file from an mzML
- Generating a set of random chemicals and creating the output mzML in fullscan and top-N mode
- Seeding from an existing mzML file

**Comment by vinnydavies** [comment]
Think this is already done. Need to double check that the current ones are still working and add a few new examples. DIA, SmartROI and sequence manager

**Comment by sdrogers** [comment]
Could you link them here please?
I’m not sure I’ve seen all the above, but that obviously doesn’t mean they don’t exist!

**Comment by joewandy** [comment]
> Could you link them here please?
> I’m not sure I’ve seen all the above, but that obviously doesn’t mean they don’t exist!

The notebooks are here https://github.com/sdrogers/vimms/tree/master/examples. These are the examples used for the paper (maybe best not to change them too much?). 

Also I just checked, for the three tasks above, they're scattered in different notebooks.

- **Creating a chromatogram / fragment pickle file from an mzML**.
    - See [01. Download Data.ipynb](https://github.com/sdrogers/vimms/blob/master/examples/01.%20Download%20Data.ipynb) section c (there are other stuff in the notebook).
- **Generating a set of random chemicals and creating the output mzML in fullscan and top-N mode**
    - First download and parse the HMDB database to get all the chemicals, see [01. Download Data.ipynb](https://github.com/sdrogers/vimms/blob/master/examples/01.%20Download%20Data.ipynb) section b.
    - Then run for fullscan mode. 
        - For a single sample, see [02. MS1 Simulations.ipynb](https://github.com/sdrogers/vimms/blob/master/examples/02.%20MS1%20Simulations.ipynb). 
        - For multiple samples, see [03. Multiple Samples Example.ipynb](https://github.com/sdrogers/vimms/blob/master/examples/03.%20Multiple%20Samples%20Example.ipynb).
    - No example to run in top-N yet.
- **Seeding from an existing mzML file**
    - See [04. Top-N Simulations.ipynb](https://github.com/sdrogers/vimms/blob/master/examples/04.%20Top-N%20Simulations.ipynb)

Maybe for each listed task, best to put them into a single notebook?

**Comment by sdrogers** [comment]
Yes, single notebooks for each of those simple cases, please. Separate from the paper ones (which should just be updated to reflect the new split between repositories).

@vinny are you working on notebooks?

If not, any volunteers?

--
Dr Simon Rogers
Senior lecturer, School of Computing Science, University of Glasgow

**Comment by joewandy** [comment]
> If not, any volunteers?

I'm doing it

**Comment by vinnydavies** [comment]
I was working on examples for the sequence manager. Some part of those examples can be added into one of the examples that already exist. We should also add DIA examples

**Comment by joewandy** [comment]
1. Data
1.1 Creating a chromatogram / fragment pickle file from an mzML
1.2 Generating a set of random chemicals and creating the output mzML in fullscan and top-N mode
1.3 Seeding from an existing mzML file

2. Methods
2.1. full scan
2.2. top-n
2.3. DIA
2.4 smartROI
2.5. Optimal controller

3. MultiSampleMethods
3.1 sequence manager
3.2 gridsearch (added)
3.3 DsDA
... others to be added

4. Evaluation
4.1. Scoring (added)
4.2 heatmap (edited)

**Comment by joewandy** [comment]
Seems that @vinnydavies has done it
