### ISSUE TITLE
DsDA Experiment

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#10]
- Some classes have been developed to perform our own DsDA-style experiment (but with our own scoring system, peak picking with mzMine etc). It’s not quite finished and need to be tested on the instrument.
- Needs to either be linked to R or need Corey to reply so that we can implement our own version
- Potentially need to test this against RepeatedController and OptimalController

**Comment by sdrogers** [comment]
Isn't this waiting for sequence controller stuff in vimms-fusion? Without that, it would be very tedious to keep re-starting?

**Comment by joewandy** [comment]
To be discussed in issue #39
