### ISSUE TITLE
Generate chemicals from mzML

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#101]
mzML -> make ROIs -> filter them -> make each into an unknown chemical
- Create new chromatogram sampler that takes an ROI from mzML as the input, and produces chromatogram.
- Also a new MS2 sampler that takes the ms2 peaks from the mzML file. (edited)

**Comment by joewandy** [comment]
Another use case is if we have a big database of ROIs/chromatograms extracted from mzML, and want to run them through the simulator.

**Comment by sdrogers** [comment]
the second bullet in the initial issue should be separate...created as #129
