### ISSUE TITLE
Generate chemicals from paired formulae + spectra

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#102]
Also, say we have a file with a load of formulas and their spectra. It would be good to generate data such that it sampled formulas from this and then assigned the correct spectrum

If the file format is e.g. mgf, we can derive the formula from SMILES. Use that to get the formula + correct spectrum.

but maybe we want to start with something more general

**Comment by joewandy** [comment]
Old note:

Let's say there are 500 chems from HDMB. We want to generate them for simulation, and assign each chemical a unique spectra from mgf files. How do we do that? Right now it doesn't seem straightforward at all.

- A set of chemicals can be drawn from a well of the autosampler.
- Need to capture this notion.
- Could use a generator to generate multiple wells?

**Comment by sdrogers** [comment]
The second part is done

**Comment by sdrogers** [comment]
Suggested solution:
1. Need to be able to create databases, like the current HMDB one
2. When we sample from a database we need to store some kind of accession in the `KnownChemical` object
3. The `.mgf` file (or `.msp`) would use the same accessions
4. Create an MS2Sampler that then picked the spectrum from the ID of the `KnownChemical`

At the moment, the MS2 sampler can be passed something called `formula` suggest re-name this to `known_chemical` to make things clear. The MS2 sampler then simply has to pick the spectrum with accession equal to `known_chemical.accession`
