### ISSUE TITLE
Add option for Optimal Controller to run as part of Sequence Manager

### ISSUE THREAD

**Issue by vinnydavies** [glasgowcompbio/vimms#124]
Currently optimal controller needs to be ran as a loop of the same controller. It should be straight forward to make this into a variation of sequence manager

**Comment by joewandy** [comment]
Would be nice if this can also go into the sequence manager? https://github.com/sdrogers/vimms-fusion/blob/master/analysis/experiment_2020_09/02_Top%20N%20with%20Persistent%20Exclusion%20List.ipynb

**Comment by sdrogers** [comment]
Let's think about this -- it's a general problem that somehow the state of the controller needs to be passed onto the next controller

**Comment by joewandy** [comment]
Yeah it was already discussed before too in https://github.com/sdrogers/vimms/issues/39 (see last comment there).

**Comment by vinnydavies** [comment]
easy enough to just update schedule between each sample, but I guess thats a quick fix. For the more advanced fix we'd need to remember that we wouldnt necessarily want to pass things on each time
