### ISSUE TITLE
Update data creation demos

### ISSUE THREAD

**Issue by vinnydavies** [glasgowcompbio/vimms#135]
The examples in vimms/demos/01. Data are all out of date and unlikely to work. These need updating. By the looks of it, this involves copying all the chemical creation tests across from tests and updating the text and file paths

**Comment by sdrogers** [comment]
They use the old code don't they? They should still work. Are you suggesting we replace them with ones using the new classes? I'm happy with that, as long as we don't change any notebooks from the original paper (and they need to all work as they did).
I guess by demos you don't mean the paper ones though, right?

**Comment by vinnydavies** [comment]
Don't think some parts of data creation in demos and examples will be working now, but might be wrong. We did have some code duplicates at some point though, so it may just be the stuff that I have implemented that is broken. My reason for thinking they are broken is that the dataset creation in sequence manager was broken because of the changes. Either way we should at least replace the demos with the new classes if that is what we are going to use from now on

**Comment by sdrogers** [comment]
Ok, sure. I’ll take a look at making new ones. Be useful if you had a specific example of what from the old is broken? To see if we want to be bothered to fix it or just ditch it.

**Comment by vinnydavies** [comment]
anything that uses `extract_roi` will be broken. There may well also be some import errors because things have changed location

**Comment by sdrogers** [comment]
@vinnydavies just ran them and they all worked....
However, will make a new one for the new classes.

**Comment by sdrogers** [comment]
actually, that's not quite true. I had to change two paths because test fixtures had moved
