### ISSUE TITLE
Sequence manager improvements

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#137]
1. Following is the [notebook](https://github.com/sdrogers/vimms-fusion/blob/master/analysis/experiment_2020_09/02_DIA_experiments_stdmix.ipynb) used in the DIA vs DDA experiment yesterday. Can the sequence manager be used to easily build this kind of workflow now, rather than having to write manual loops like what I did in the `run_DIA_experiment` of the notebook?

2. With a small modification to (1) to keep persistent states across runs (and possibly related to #39), we should also be able to do the experiment in [this notebook](https://github.com/sdrogers/vimms-fusion/blob/master/analysis/experiment_2020_09/03_Top%20N%20with%20Persistent%20Exclusion%20List.ipynb) too using the sequence manager. PS. Haven't had the chance to run this notebook yet.

3. For future experiments, it would be nice if the sequence manager can export to CSV file. See example below for the format that can be loaded into the Sequence Setup program in XCalibur (which is used to manage the LC). I had to manually typed all the entries to prepare for the DIA vs DDA experiment, which is a bit tedious.

[stdmix_sequence.txt](https://github.com/sdrogers/vimms/files/5187878/stdmix_sequence.txt)

![image (1)](https://user-images.githubusercontent.com/2523391/92468876-c5f45280-f1cb-11ea-8093-332a291ab392.png)

**Comment by vinnydavies** [comment]
Yes, you can set up the sequence manager to do this, but not sure how much more efficient it would be. It terms of keeping states through different runs then thats something that would need to be added (relates to #124). It could be added to sequence manager without doing #39, but it would be a bit of a hack

**Comment by sdrogers** [comment]
Quite a lot going on here...
1. Running a fixed set of controllers over a series of injections, where each has different constructor parameters is always going to be a loop. I'm not sure whether the code above is any less neat than that? I cannot see any way of doing it without supplying a list of controller objects that doesn't require horrific parameter argument lists?
2. I don't know what the entries in that csv file mean? I.e. do we need to make such a file to run things? My understanding is that Xcaliber needs to know the order of injections, and nothing else. Does these have to be defined a-priori? I.e. we couldn't build a meta controller that chose what to inject? Presumably the file names in he second column are just for your records.
3. For the persistent exclusion, this just requires a very general abstract sequence manager where the controller returns some state at the end, which is then passed to the next one. i.e. `get_state` and `set_state`

**Comment by joewandy** [comment]
> I don't know what the entries in that csv file mean? I.e. do we need to make such a file to run things? My understanding is that Xcaliber needs to know the order of injections, and nothing else. Does these have to be defined a-priori? I.e. we couldn't build a meta controller that chose what to inject? Presumably the file names in he second column are just for your records.

We turn off the mass spec when running this sequence from xcalibur, but we still need it to control the LC, so yes, we do need such a file that will loaded into Xcalibur (or manually typed) to define the order of injections when running things. The important columns are the `Position` which defines the position in the auto-sampler, and also the `Inst Meth` which defines which method to run (the screenshot shows a standard 26-mins injection, but we could do others, e.g. the 5 mins no-injection run).

So both the sequence of controllers from our side and this sequence of injections from xcalibur side need to be synchronised. Yesterday when manually creating this file, I nearly made a mistake of having an extra row in the entries. Better if we can export the CSV from our side, and load it on xcalibur to minimise data entry error.

**Comment by joewandy** [comment]
Can be done as part of issue #39 ? This will make it easier to run things on the instrument the next time if we don't need to create the CSV by hand to load into xcalibur.

**Comment by joewandy** [comment]
No resource to do.
