### ISSUE TITLE
DIA Swath controllers

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#14]
Need a controller that mimics standard DIA (i.e. non-tree).

need to parameterise the MS2 scans: number of scans, their width, and to what extend they overlap.
Suggest:
- `ms2_scan_start` = m/z of start of first - better name?
- `num_ms2_scans` = number of scans
- `ms2_scan_width` = width (Da)
- `ms2_scan_overlap` = overlap (Da) (must be `< ms2_scan_width`)

so, if `ms2_scan_start = 50`, `num_ms2_scans = 6`, `ms2_scan_width = 20` and `overlap = 5` then the scans would be (in terms of isolation window):
1. 50 to 70
2. 65 (70-5) to 85
3. 80 to 100
4. 95 to 115
5. 110 to 130
6. 125 to 145

It would add these ms2 scans to the queue and then add an ms1 scan at the end.

Q for comment: how should this fit into the `Controller` hierarchy. Inherit from `Controller`?
Q for comment2: should `Controller` and other high level classes be in a different file (i.e. not TopN)? @joewandy ?

**Comment by vinnydavies** [comment]
this is already implemented, except for the overlap. Setting `dia_design=’basic’` and `num_windows=10`, would do 10 even sized windows spread across the whole rt range

**Comment by sdrogers** [comment]
Would it do the overlap?
