### ISSUE TITLE
Target creation from toxid should filter by polarity

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#144]
At the moment it is taking all, but noticed that the files look like:

>36,L-Lysine,C6H14N2O2,+,,18.35,1000,1,,,,,
37,L-Arginine,C6H14N4O2,+,,19.93,1000,1,,,,,
38,Phenolsulfonphthalein,C19H14O5S,-,,5.69,1000,1,,,,,
39,Thymidine,C10H14N2O5,-,,6.45,1000,1,,,,,

And therefore include both +ve and -ve entries. Makes no sense to look for -ve entries in +ve mode data? @RonanDaly am I interpreting the files correctly?

**Comment by RonanDaly** [comment]
Yes, the ToxID files have both polarities.

**Comment by sdrogers** [comment]
so, we would only look for + examples in positive acquisition, right?

**Comment by RonanDaly** [comment]
Yes - that's not to say that it doesn't ionise in negative mode, just that it was never entered into the configuration file - generally the most reliable peak is used, but sometimes both modes are good.

**Comment by sdrogers** [comment]
So, in terms of creating a library of MS2 should we include the -ve ones in +ve mode or not?
