### ISSUE TITLE
Reorganise scan processing within controllers

### ISSUE THREAD

**Issue by vinnydavies** [glasgowcompbio/vimms#15]
Reorganise scan processing within controllers to remove duplications. Probably easiest to wait for #8 to be completed first

**Comment by vinnydavies** [comment]
Probably best to not mess with this old code anymore, so not going to be updating the `process_scan` code in the base controllers (`TopNController`). Instead there is a new controller called `GridController` from which future controllers can be built off which has a more organised version of `process_scan`. Assuming future controllers are built from here then that sorts this issue

**Comment by joewandy** [comment]
How's the `process_scan` inside `GridController` more organised in comparison to the old one, may I ask?

**Comment by vinnydavies** [comment]
@mcbrider5002  cleaned it up a little bit. Can clean it up more if you want, could be worthwhile. Suggest you clean that controller up rather than the original base controllers, so we dont mess up any of the old controllers
