### ISSUE TITLE
Write controller to do top 4, with then some ms2 with multiple windows

### ISSUE THREAD

**Issue by vinnydavies** [glasgowcompbio/vimms#151]
Write a controller that does the follow sequence
- ms1 scan
- top 4 (individual ms2 scans)
- multi windows for pairs of ions(e.g ion1 + ion2, ion1 _ ion3, ...)
- multi windows for trios of ions
- multi windows for all 4 ions

**Comment by sdrogers** [comment]
Top-N with scans
[1], [2], ... , [N], [1,2], [1,3], [2,3], ..., [1,2,...,N]
So, eg with N=3:
[1], [2], [3], [1,2], [1,3], [2,3], [1, 2, 3]

**Comment by sdrogers** [comment]
i.e. top-3 maybe more sensible than 4.
