### ISSUE TITLE
TopN controller: mzs shape not the same as intensities shape

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#169]
Saw this in the debugger while making the test for the TopN controller .. it looks wrong

![image](https://user-images.githubusercontent.com/2523391/93887773-07fab980-fcdf-11ea-8b42-7f008c08a45b.png)

Above `mzs.shape` is (559,) while `intensities.shape` is (559, 1). 

This will lead to problem later on, because the next line `np.argsort(intensities)[::-1]` won't work.

**Comment by sdrogers** [comment]
Doesn't seem like a controller issue -- something in the MS class?

**Comment by sdrogers** [comment]
Which test was actually running this? I.e. how were the chemical objects created?

**Comment by joewandy** [comment]
It's the `test_TopN_controller_advanced_params` test in this commit: https://github.com/sdrogers/vimms/commit/0a26098db3498d5d08d29c32ac5db77b8add258b. 

I also added an assert line to check that `mzs.shape == intensities.shape`. Other tests still work fine, so it seems that the problem only happens here.

**Comment by joewandy** [comment]
Related to issue #162

**Comment by sdrogers** [comment]
That's odd, because that list comes from the chemical classes
