### ISSUE TITLE
Update BEER_CHEMS

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#173]
Update BEER_CHEMS and remove lines 37-39 in conftest.py

**Comment by vinnydavies** [comment]
what was this @joewandy? Is this something I still need to do?

**Comment by joewandy** [comment]
Yes the beer chems need to be regenerated properly since it was created with very old codes. Once it's done that [these lines](https://github.com/glasgowcompbio/vimms/blob/master/tests/conftest.py#L36-L38) can go away.

**Comment by joewandy** [comment]
Also it would fix the falling unit test here https://github.com/glasgowcompbio/vimms/runs/2495493626

**Comment by joewandy** [comment]
Done
