### ISSUE TITLE
Scan time sampling

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#18]
Current scan time sampling code requires a value of `N` in order to sample.
This is because of the dependence of time on `N`.
In DIA controllers, there is no `N` and it seems to default to zero somewhere which then results in no time being sampled at:
https://github.com/sdrogers/vimms/blob/b8b78c64389a8c2afe903f4e3bd2fe818b408720/vimms/MassSpec.py#L457

Options:
1. Default to N = 10 if N = 0
2. (better) more general method for scan time sampling?

**Comment by sdrogers** [comment]
Currently fixed by setting the CURRENT_TOP_N attribute in ScanParameters for all scans to 10.

**Comment by sdrogers** [comment]
I wonder whether a more sustainable long-term solution is making it more common to pass a scan time dictionary to the MS object. It can currently handle this:
https://github.com/sdrogers/vimms/blob/c5c0d77e4a4f587588d77b29c61d23511f8d39c8/vimms/MassSpec.py#L437-L438
The dictionary could, presumably hold a method that could generate random times or constants?

**Comment by sdrogers** [comment]
From meeting 24th July - this method for setting times should be the default so that it doesn't rely on the `peak_sampler`
Action required:
A default dictionary should be provided (as a constant in `ViMMS.Common`) with standard params (1: 0.4, 2:0.2).

**Comment by joewandy** [comment]
- Timing should always be provided by a `scan_timing` dictionary (see [MassSpec.py](https://github.com/sdrogers/vimms/blob/master/vimms/MassSpec.py#L440-L449)). Make that the default. 
- Remove timing information from `peak_sampler` object in DataGenerator.py
- The dictionary method is going to work for most things, but maybe not all, and we might want more flexibility in future, i.e. dictionary allows different times for MS1 and MS2, but not, say, for different types of MS1. 
- Create a new class that we can sample scan times from. When sampling new times, pass it all scan parameters. At the moment just get the method to raise a not implemented exception please, and remove all logic from e.g. the method in issue #46 so it just calls yours

**Comment by joewandy** [comment]
Done
