### ISSUE TITLE
Automate MS-DIAL

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#191]
We can run MS-DIAL from the command line (refer to http://prime.psc.riken.jp/compms/msdial/consoleapp.html). Is it possible to script it for our experiments?

To test the console app:
1. Download MS-DIAL and extract. The `MsdialConsoleApp.exe` program can be found in the same location as the GUI app.
2. Download the sample data file: http://prime.psc.riken.jp/compms/msdial/download/demo/MsdialConsoleApp%20demo%20files.zip (link also available from the web page above), and extract.
3. Copy all the extracted files to the same location as where MS-DIAL is (simplest way, or you need to adjust path etc).
4. Run the batch file `MsdialConsoleApp.bat`. This will run 3 example analysis: GC/MS, LC-MS/MS DDA, and LC-MS/MS DIA. Can ignore the GC/MS one.
    - Edit `Msdial-lcms-dia-Param.txt` to adjust the path to the input DIA file in the LC-MS/MS DIA folder. 
4. The sample DDA analysis runs fine. However the DIA can't run ...
```
MsdialConsoleApp.exe lcmsdia -i .\LCMS_DIA\ -o .\LCMS_DIA\ -m .\LCMS_DIA\Msdial-lcms-dia-Param.txt
Loading library files..
Start processing..
Could not load file or assembly 'MsdialCommon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```
Seems like some library loading / path problem? To check later..

**Comment by sdrogers** [comment]
Looks like that might be hard to fix. Think kei might have found something similar and an older version of MSDIAL worked ok (I _think_ the latest version just adds some ion mobility stuff that we’re not interested in)

**Comment by sdrogers** [comment]
We just need to make sure we’re using the version described in the CorrDecon paper

**Comment by joewandy** [comment]
'Data were processed by MSDIAL version 4.12'

http://prime.psc.riken.jp/compms/msdial/download/repository/MSDIAL%20ver%204.12.zip

Will test later

**Comment by sdrogers** [comment]
![Screenshot 2020-10-08 at 14 19 31](https://user-images.githubusercontent.com/611683/95463955-5069d680-0971-11eb-92d5-055f739eda09.png)

Looks like you can drop back into v3.22 if necessary

**Comment by joewandy** [comment]
v4.12 works on both the GUI and command line.

However it seems that from the terminal, the [DIA mode only accepts input file in ABF format](http://prime.psc.riken.jp/compms/msdial/consoleapp.html) ..

![image](https://user-images.githubusercontent.com/2523391/95483143-cb89b780-0986-11eb-8025-ca7e4cda978c.png)

(the DDA mode works with mzML files)

So we need to install ABF converter: https://www.reifycs.com/AbfConverter to get the DIA mzML files to this format. As a pre-requisite, this needs MSFile from thermo (install MSFileReader version 3.0 SP2 or higher except ver. 3.1 SP4).

**Comment by sdrogers** [comment]
I don't think converting from .raw is going to work. Remember that the RAW files had the apodization issue (peak smudging).

**Comment by sdrogers** [comment]
but looks like maybe that converter will convert from .mzML

**Comment by joewandy** [comment]
Ignore the ABF stuff above. Version 4.12 works with mzML file from both the GUI and terminal (was mistakenly using an .mzXML file to test).

**Comment by joewandy** [comment]
See: 
- http://www.metabolomics-forum.com/index.php?topic=1557.0
- http://www.metabolomics-forum.com/index.php?topic=1558.0

For now, we ended up using two different versions of MSDIAL:
- v4.24 for the DDA mode. The msp matching works on this version but not on v4.12.
- v4.12 for the DIA mode. The DIA mode runs on this version but not on v4.24.

**Comment by joewandy** [comment]
Have created a script `msdial_wrapper.py` that can be used to launch MS-DIAL, either on a single mzML or a set of mzML files. However for multiple mzML, it seems tricky to enable CorrDec.
