### ISSUE TITLE
Duplicate MZMine Runner Code

### ISSUE THREAD

**Issue by mcbrider5002** [glasgowcompbio/vimms#194]
There is an old 'pick_peaks' function which lives in:
https://github.com/sdrogers/vimms/blob/fc0cb089afa1152c0a4dce9387d0b9436caa292e/vimms/PythonMzmine.py

However, the mass_spec_utils library contains a newer version, which for example correctly handles an inconsistency in MZMine batch files between versions. Seen here:
https://github.com/sdrogers/mass-spec-utils/blob/master/mass_spec_utils/data_processing/mzmine.py

Remove old pick_peaks function, and other items abstracted into mass_spec_utils library?

**Comment by joewandy** [comment]
I noticed that too yesterday. Let's remove the old 'pick_peaks' and use the current one in mass-spec-utils. Should make sure not to break existing codes when doing this.

**Comment by joewandy** [comment]
Done
