### ISSUE TITLE
Generic exclusion codes

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#217]
Many controllers now use Top-N exclusion windows, but there is no reason they couldnt use the weightedDEW or smartROI exclusion criteria. We should be able to extract these exclusion methods into its own classes that can be used elsewhere easily.

**Comment by joewandy** [comment]
Fixed in branch #iss_217 by introducing two exclusion classes: [TopNExclusion](https://github.com/glasgowcompbio/vimms/blob/master/vimms/Exclusion.py#L155-L223) and [WeightedDEWExclusion](https://github.com/glasgowcompbio/vimms/blob/master/vimms/Exclusion.py#L226-L255). These contain the exclusion logic that can be reused in different controllers. See example [here](https://github.com/glasgowcompbio/vimms/blob/master/vimms/Controller/topN.py#L30) and [here](https://github.com/glasgowcompbio/vimms/blob/master/vimms/Controller/topN.py#L144).

I had to modify the TopN controller to work with this, and since everything extended from TopN (even the ROI controller) some of them had to be modified as well. Instead of modifying the `OptimalTopNController` and `PurityController`, I [commented](https://github.com/glasgowcompbio/vimms/blob/master/vimms/Controller/old.py) them out since we likely won't work on them anymore.

I also found a small bug while looking through the DEW codes. The same precursor ions were excluded twice: [once when the MS1 is processed (and MS2 scans were generated)](https://github.com/glasgowcompbio/vimms/blob/c455b3cda284fb10e2919702e525762566d64caf/vimms/Controller/topN.py#L113), and [another time when the MS2 scan is processed](https://github.com/glasgowcompbio/vimms/blob/c455b3cda284fb10e2919702e525762566d64caf/vimms/Controller/topN.py#L148-L156). The former was added when we put in codes to deal with ms1 shift, in which case the latter should be removed but it wasn't. Effectively we're extending the RT exclusion window to be slightly bigger than it is. To fix this, I got rid of the second exclusions (when MS2 scans are processed), so it is only done once when the MS1 is processed (and MS2 scans were generated). Below show some simulated results (with fixed scan times) of TopN before and after fixing this. The frag events seem to be broadly similar? So hopefuly this won't affect the results too much. 

Before
![image](https://user-images.githubusercontent.com/2523391/118473979-7a9f2600-b702-11eb-8502-c4960ee69962.png)

After
![image](https://user-images.githubusercontent.com/2523391/118474026-87237e80-b702-11eb-9f7b-8ad606723666.png)

Have done testing by comparing unit test results to make sure that the results are still the same before and after refactoring, and also after fixing the exclusion bug above.

**Comment by justinjjvanderhooft** [comment]
The Figures look - overall - pretty similar to me - with a small shift to the right hand side. What do the stats in terms of coverage and no. of MS1 & MS2 scans say? Probably a very similar picture?! Of course, it will make a (tiny) difference in terms of when a LC-MS peak gets fragmented.....
