### ISSUE TITLE
Add more logging to the ROI controller so we know the processing time vs Top-N

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#22]
Twice the number of logs

Need to do this before the experiment

**Comment by sdrogers** [comment]
@joewandy the processing time can be computed purely in python. Doesn't need to be on the machine. The time we want to know is the difference between the time between receiving an MS1 scan and creating all the MS2 scans for:
- TopN
- SmartROI

**Comment by sdrogers** [comment]
The machine can tell us communication delay, but that's not what we're interested in.
