### ISSUE TITLE
Is it possible to also support Waters WRENS API?

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#28]
Look into this more 

https://www.google.com/search?q=Waters+Research+Enabled+Software+suite+(WREnS)&oq=wat&aqs=chrome.0.69i59l2j69i60j69i57j69i61j69i60j0.1145j0j7&sourceid=chrome&ie=UTF-8

**Comment by sdrogers** [comment]
@everyone: is this something we want to devote time / effort to? If "yes", we could contact Corey and see if he was interested in trying some things.

**Comment by sdrogers** [comment]
or contact Waters direct

**Comment by joewandy** [comment]
Found this project that interfaces with WREnS: https://origami-ms.lukasz-migas.com/ as an example. Here's how they do it:
1. Write a C# script that accepts some command-line parameters from users. It would use the WREnS API to connect to MassLynx and control the mass spec. [Example](https://github.com/lukasz-migas/ORIGAMI/blob/master/ORIGAMI_MS/scripts/CIU_LIST.cs).
2. Compile 1 to get a command-line program. [Example](https://origami-ms.lukasz-migas.com/user-guide/compilation/).
3. From Python, we can create a subprocess that calls the result of 2. [Example](https://github.com/lukasz-migas/ORIGAMI/blob/71722b2d464e6907ec9b56c1b2417b64c9fea8a9/ORIGAMI_MS/source/ORIGAMIMS.py#L577).

For ViMMS, we could add another bridge class e.g. `WrensBridge.cs` and a mass spec class e.g. `WrensMassSpec.py`. Hopefully everything else should work fine once we swap out the mass spec? But I'm not sure if it would allow us to handle incoming scans interactively like IAPI? Would need to check the documentation for that, or ask Waters.

Not sure if we want to dedicate much time to this? What do you think? @sdrogers @RonanDaly

**Comment by RonanDaly** [comment]
Not sure if this is the wisest use of time, given that we don't have a Waters to test on arbitrarily. I would want us to have guaranteed access, otherwise there might be a whole lot of effort for nothing.

**Comment by joewandy** [comment]
👍 Let's close this issue.
