### ISSUE TITLE
Make the unit tests faster

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#31]
They are unnecessarily slow
1. Reduce number of chemicals when generating data
2. Reduce acquisition time

**Comment by sdrogers** [comment]
Anyone on to this? It's a 10 minute job..

**Comment by RonanDaly** [comment]
As far as I can tell, the tests are merely that the methods run and for the existence of certain objects after they have run. Why not say, 2 chemicals and a short acquisition time (is it that we might miss the chemicals with a short time?).

**Comment by RonanDaly** [comment]
Have updated tests to pytest framework with commit 98957d96333de353b4f4adbf40a6e2d0c547114f. To run tests, use:
```
python -m pytest tests/
```
To view output, use:
```
python -m pytest -s tests/
```
