### ISSUE TITLE
Add peak only and XCMS to sequence manager

### ISSUE THREAD

**Issue by vinnydavies** [glasgowcompbio/vimms#34]
Once we have the peak only (Simon) and XCMS (Ronan) peak picking methods set up to work within the ViMMS / Python framework, it would be good to add them (Vinny) to the sequence manager

**Comment by joewandy** [comment]
how's the peak picking results from `peakonly`? is it good?

**Comment by sdrogers** [comment]
it's fast, and looks ok
Really easy to run (their latest release has a GUI). Open an .mzML, click "pick peaks", wait a minute or so...

**Comment by joewandy** [comment]
Not having a good peak picking method is the main thing that prevented us from creating a decent xcms-alternative in Python, right? So now it's all there.

**Comment by sdrogers** [comment]
Yes, possibly. Good point.
Probably needs someone who knows that they’re on about to look at the output though...

Simon Rogers
simon.d.rogers@gmail.com

**Comment by joewandy** [comment]
Another question that came up in meeting: if we pass peakonly a partial chromatogram, could it still identify that it's a peak or not?

**Comment by joewandy** [comment]
To be discussed in issue #39
