### ISSUE TITLE
Horrible scan time method calling

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#46]
Get rid of all this logic...if we get to this method, we should just sample times from the new `peak_sampler`:
https://github.com/sdrogers/vimms/blob/49d48c816bd5cffe091c7031cb35a54b01d73c49/vimms/MassSpec.py#L455-L469

to be completed after #18

**Comment by joewandy** [comment]
Once we get rid of the kde stuff (the `ps` object), I think we don't need to use this specific [scikit-learn version](https://github.com/glasgowcompbio/vimms/blob/master/Pipfile#L12) anymore. The pickled beer chems relies on the kde object being in the following particular location:
```
    def load_obj(filename):
        """
        Load saved object from file
        :param filename: The file to load
        :return: the loaded object
        """
        try:
            with gzip.GzipFile(filename, 'rb') as f:
>               return pickle.load(f)
E               ModuleNotFoundError: No module named 'sklearn.neighbors.kde'
```

**Comment by joewandy** [comment]
Done
