### ISSUE TITLE
Update readme for new testing code

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#47]
Please update readme file to reflect change to purest...can we run individual tests now? Tests are quick so doesn't matter so much if not.

**Comment by joewandy** [comment]
What do you mean, 'purest'?

**Comment by RonanDaly** [comment]
I think he means pytest.

**Comment by sdrogers** [comment]
He does

**Comment by RonanDaly** [comment]
Done, commit 22015f0e2fea7480155bb1048bab76bf54cbcfc8.
