### ISSUE TITLE
Making multiple precursor windows match MS behaviour

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#48]
At the moment, it is possible to send a list of windows (parameterised by start and end point) to the MS.
We need to see if:
1. This is the format that the real MS accepts for multiple windows
and, if not,
2. Change our code to reflect the real MS so that DIA controllers will work with both real and simulated MS.

**Comment by joewandy** [comment]
I  guess (1) can be in any format we want, because when running on the real MS, we translate (1) to the actual IAPI calls. See https://github.com/sdrogers/vimms-fusion/blob/master/vimms_fusion/MassSpec.py#L162-L173.

**Comment by sdrogers** [comment]
Ah, ok - do we know how to do multiple isolations in the actual IAPI?

**Comment by sdrogers** [comment]
Also, just remembered something else...
All MS2 need at least one precursor m/z (I think they can have multiple), so it makes more sense to me that the controllers, if asking for an MS2 scan, parameterise it with one (or more) precursor m/z and isolation widths, rather than m/z windows, just for coherence?

**Comment by sdrogers** [comment]
I’m referring to the list of window ends that is used in some of the DIA controllers...we’ll also have to put precursors in them for the simulator for the MS2 scans to write to the .mzml

**Comment by joewandy** [comment]
> Also, just remembered something else...
> All MS2 need at least one precursor m/z (I think they can have multiple), so it makes more sense to me that the controllers, if asking for an MS2 scan, parameterise it with one (or more) precursor m/z and isolation widths, rather than m/z windows, just for coherence?

It's [already parameterised by precursor m/z and isolation width](https://github.com/sdrogers/vimms/blob/master/vimms/MassSpec.py#L100-L101) to match what IAPI requires.

Then given those two values, we have [a method to get the isolation window](https://github.com/sdrogers/vimms/blob/master/vimms/MassSpec.py#L137-L148) in the simulator.

**Comment by joewandy** [comment]
> Ah, ok - do we know how to do multiple isolations in the actual IAPI?

Seems like it should work (although never actually tried it on the real machine). Take a look at the table at the end of the attached word doc. That lists the parameters to use when specifying an IAPI custom scan. Entries with * can be specified as multiple values using ';' as the delimiter. This includes the `PrecursorMass` and `IsolationWidth` parameters.

[AnalysisOfMZML.docx](https://github.com/sdrogers/vimms/files/4975645/AnalysisOfMZML.docx)

**Comment by sdrogers** [comment]
It is and that’s what we’ve been mainly using, but we also seem to permit a list of windows defined by their upper and lower bounds (*without* a precursor) and I think we shouldn’t allow that. If there is no precursor, it will have to be added somewhere to make the mzML writing work, and it seems most sensible to have it added by the controller?

**Comment by joewandy** [comment]
Done as part of #106?
