### ISSUE TITLE
Add scans one-by-one into the queue rather than the entire block

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#5]
Still not done ...

**Comment by sdrogers** [comment]
Do you mean adding them as they are created into our queue?

**Comment by sdrogers** [comment]
Not sure I agree that this is a priority though

**Comment by joewandy** [comment]
It will be, if the number of scans from our controller is a lot lower than the instrument's one?

**Comment by sdrogers** [comment]
don't understand what you mean?
I thought this was just a speed up, so one of our MS2 scans could be sent to the machine before we'd finished making all the MS2 scans.
It could therefore speed things up a little?
