### ISSUE TITLE
Chemical creator seems broken for creating a set of chemicals from scratch

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#62]
![image](https://user-images.githubusercontent.com/2523391/90125170-78fe9700-dd59-11ea-8343-cfd97edb6366.png)

See https://github.com/sdrogers/vimms/blob/master/demo/01.%20Data/03.%20Generating%20a%20set%20of%20random%20chemicals.ipynb

**Comment by sdrogers** [comment]
How do all the tests work then?

**Comment by sdrogers** [comment]
Have you run notebooks 1 and 2? In number 3, the one above, the cell that fails says that it needs the ROI data from notebook 1...

**Comment by sdrogers** [comment]
The issue isn't in `ChemicalCreator`, it's a problem with paths etc in that notebook. It's looking for ROI sources in `<base_dir>/beers/datasets` where (presumably) `<base_dir>` is as defined in notebook 1.

Will leave to @vinnydavies to fix this.

1. `base_dir` needs to be defined in `03. Generating a set of random chemicals`. Should it be the same as `data_dir`?
2. Fix the bit that Joe points out above -- I think it's just looking for files in the wrong place.

**Comment by joewandy** [comment]
> Have you run notebooks 1 and 2? In number 3, the one above, the cell that fails says that it needs the ROI data from notebook 1...

I haven't tried running the notebook, sorry. Was just putting what Vinny told me on slack yesterday into this issue for tracking.

> How do all the tests work then?

They work, but some have their own issues that need to be fixed (see https://github.com/sdrogers/vimms/issues/58).

**Comment by vinnydavies** [comment]
I've updated the demo, so this is working now
