### ISSUE TITLE
Noise class is a bit restrictive?

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#69]
Current Noise class is a single object passed to the MS.

I can easily imagine that we will want different noise for MS1, and MS2, and for mz and intensity.

Suggest a bit of a refactoring so that the MS takes two objects (one to generate noise for mz and one for intensity). In practice, the same object could be passed to both -- the noise generator doesn't care if it is making noise for m/z or intensity.

Each noise generator is passed the `ms_level` and can decide if it wants to behave differently for different levels.

Any thoughts?

**Comment by sdrogers** [comment]
as an aside -- doc string in MS is now out of date

**Comment by sdrogers** [comment]
Also, is this code now redundant?
https://github.com/sdrogers/vimms/blob/951fc55311f3a6409c3397b6a2b8cd6fa7f3081e/vimms/MassSpec.py#L577-L587

**Comment by joewandy** [comment]
> Suggest a bit of a refactoring so that the MS takes two objects (one to generate noise for mz and one for intensity). In practice, the same object could be passed to both -- the noise generator doesn't care if it is making noise for m/z or intensity.

Sounds cleaner. Let's go with this.

**Comment by joewandy** [comment]
> Also, is this code now redundant?
> https://github.com/sdrogers/vimms/blob/951fc55311f3a6409c3397b6a2b8cd6fa7f3081e/vimms/MassSpec.py#L577-L587

Yeah it's no longer used anywhere, and can be deleted.
