### ISSUE TITLE
Create test case for the chemical generation process

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#71]
Should cover a number of scenario:

1. Generate known chemicals from scratch -- with randomly samples / CRP peaks in the ms2 spectra
2. Generate unknown chemicals -- with intact ms2 spectra sampled from mzML files
3. Generate a mixture of known + unknown chemicals -- with mgf file for the correct spectra for the known compounds + mzML file for the unknown compounds.

Last one is needed for issue #2

**Comment by sdrogers** [comment]
awaiting #2
