### ISSUE TITLE
DsDA Example Broken

### ISSUE THREAD

**Issue by vinnydavies** [glasgowcompbio/vimms#73]
The DsDA example from the original ViMMS paper is broken /examples/01. vimms (Wandy et al 2019)/DsDA. The code appears to be severely out of date. The mass spec no longer takes the schedule file that DsDA needs to run, it also doesn't use `environment`

**Comment by uliebal** [comment]
in ``examples/01. vimms (Wandy et al 2019)/01. Download Data.ipynb``
the function ``extract_roi`` has moved to ``FeatureExtraction`` file and should be loaded as:
``from vimms.FeatureExtraction import extract_roi``

**Comment by joewandy** [comment]
> in `examples/01. vimms (Wandy et al 2019)/01. Download Data.ipynb`
> the function `extract_roi` has moved to `FeatureExtraction` file and should be loaded as:
> `from vimms.FeatureExtraction import extract_roi`

Thanks for noticing that @uliebal ! I've just fixed the notebooks.

If you're interested to run our project, the [demo](https://github.com/sdrogers/vimms/tree/master/demo) folder contain more examples to look at. There's also a number of test cases [here](https://github.com/sdrogers/vimms/tree/master/tests) that test the controllers and other classes in different scenarios. Feel free to raise an issue on this github if you have any question.
