### ISSUE TITLE
Create code to train model

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#75]
1. Modify the peakonly model to give a binary output
2. create method to load training data from a folder, train model, and save trained model

**Comment by joewandy** [comment]
Do we still plan to do the real-time peak picking in a controller @mcbrider5002 ?

**Comment by mcbrider5002** [comment]
@joewandy Yes, but I think we're still some ways off that. Hoping I'll get back to it in the next few months? Want to wrap up non-overlap, matching, drift, etc first...

**Comment by joewandy** [comment]
student project
