### ISSUE TITLE
Controller has too many parameters in the constructor

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#77]
When creating say the TopN or the SmartROI controllers, there are too many parameters that can be passed in. This makes the codes messy -- especially when we create a new controller that extends from an existing one, and need to pass all those parameters to the super constructor.

Example: https://github.com/sdrogers/vimms/blob/master/vimms/Controller/roi.py#L253-L269.

Should wrap all those common parameters into its own class.

**Comment by sdrogers** [comment]
Does it need a whole class? What about just a dictionary?

**Comment by sdrogers** [comment]
and would it be one class to hold options for all controllers? Or subclass for each controller?
