### ISSUE TITLE
Update examples to deal with changes to mass spec class

### ISSUE THREAD

**Issue by vinnydavies** [glasgowcompbio/vimms#82]
with the change in how the noise goes into the mass spec, some of the examples wont work anymore. Just requires a small change in most cases

**Comment by vinnydavies** [comment]
also need to change all paths to fixtures as this has been updated

**Comment by vinnydavies** [comment]
need to wait for DIA to be merged to master before that example can be updated

**Comment by sdrogers** [comment]
@vinnydavies can this be closed now?

**Comment by vinnydavies** [comment]
Changes made in branch iss_82
