### ISSUE TITLE
Missing precursor information from MS2 scans of FixedScansController

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#88]
The latest commit in https://github.com/sdrogers/vimms/pull/87 broke something in the code, it seems that the precursor information is missing from output mzML 

![image](https://user-images.githubusercontent.com/2523391/90960436-6989f700-e499-11ea-8a9f-0ee6dc89a044.png)

**Comment by sdrogers** [comment]
@joewandy this is pretty urgent -- going to break a lot of downstream things...high priority please!

**Comment by joewandy** [comment]
It only affects the FixedScansController, likely because I forgot to set this `precursor_info` dictionary (issue https://github.com/sdrogers/vimms/issues/59).

**Comment by joewandy** [comment]
Need to fix the test case (generate chemicals in a narrow range using the new codes) so we know something is always there for fragmentation.
