### ISSUE TITLE
TopN controller with an initial exclusion list

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/vimms#89]
We can create a TopN controller having an initial exclusion list that is obtained from the previous run. This way we don't fragment the same things in this run that have been fragmented in the previous run.

**Comment by sdrogers** [comment]
yep, so:
- Controller must keep track of mz and RT of things it fragments
- From this we then make an exclusion list
- Pass this list to controller N+1
- Get the things fragmented again
- Make new exclusion list by combining both sets of fragmented things....etc etc....
