### ISSUE TITLE
New simplified chemical creator

### ISSUE THREAD

**Issue by sdrogers** [glasgowcompbio/vimms#98]

**Comment by vinnydavies** [comment]
Simon said:

a data generation where it is easy to:

- Define where the formulas come from
- Define a distribution over RT
- Define a distribution over intensity
- Define where the chromatograms come from
- Define easily where the MS2 come from

I suggest the following process:

- Sample formula
- Sample RT & intensity conditioned on formula (by conditioned i just mean that the method is passed it so can do with it as it pleases). Method returns rt and intensity as we might want to sample them with dependence
- Assign a chromatogram passing formula, RT, intensity (in case we want dependence)
- Assign MS2

**Comment by vinnydavies** [comment]
Initial upload of code and notebook looks good to me. Couple of things for future improvements rather than direct comments

- should add the option to not have formula and just generate m/z from a density
- should add more structure to classes, i.e. add a base classes to ensure the inputs and outputs are consistent
- should the process of adding adducts and isotopes have its own class, similar to the way we add rt, intensity, etc?

**Comment by sdrogers** [comment]
So, for part 1, generating `UnknownChemical` objects instead?
Agree re base classes.
Not so sure about isotopes and adducts -- this would require changes within the `KnownChemical` class which I'm not sure is really necessary just now? The code for them seems pretty sound anyway?

**Comment by sdrogers** [comment]
@vinnydavies :
- added base classes to formalise things
- Left adducts / isotopes as is
- Can now generate UnknownChemicals. See e.g. https://github.com/sdrogers/vimms/blob/ae56a2ad8c25d9817b4da7c31d6211729ac84e50/vimms/Common.py#L133-L138
Which defines a dummy class that looks like a formula (it has a `mass` attribute and a `compute_exact_mass()` method) and then: https://github.com/sdrogers/vimms/blob/ae56a2ad8c25d9817b4da7c31d6211729ac84e50/vimms/ChemicalSamplers.py#L27-L31
That samples mz and puts them into `DummyFormula` objects

**Comment by sdrogers** [comment]
Now also added an MS2Sampler that can sample spectra from an .mgf file
